language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install octoprint"
  - "pip install .[develop]"
# command to run tests
script: py.test
